# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: jenkins-master
  Image: "jenkinsci/jenkins"
  ImageTag: "2.59"
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
# AdminPassword: <defaults to random>
  Cpu: "200m"
  Memory: "256Mi"
# Set min/max heap here if needed with:
# JavaOpts: "-Xms512m -Xmx512m"
  ServicePort: 8080
# For minikube, set this to NodePort, elsewhere use LoadBalancer
# Use ClusterIP if your setup includes ingress controller
  ServiceType: LoadBalancer
# Used to create Ingress record (should used with ServiceType: ClusterIP)
# HostName: jenkins.cluster.local
# NodePort: <to set explicitly, choose port between 30000-32767
  ContainerPort: 8080
  SlaveListenerPort: 50000
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
# List of plugins to be install during Jenkins master start
  InstallPlugins:
      - kubernetes:0.11 
      - workflow-aggregator:2.5
      - credentials-binding:1.11
      - git:3.3.0
      - blueocean:1.0.1
      - pipeline-github-lib:1.0
      - checkstyle:3.48
      - scoverage:1.3.2
      - ws-cleanup:0.33
      - junit:1.20
      - jira:2.3
      - slack:2.2
# Used to approve a list of groovy functions in pipelines used the script-security plugin. Can be viewed under /scriptApproval
  # ScriptApproval:
      - "method groovy.lang.Binding getVariables"
      - "new java.util.TreeMap"
      - "staticMethod java.lang.Thread currentThread"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods inspect java.lang.Object"
      - "field java.util.HashMap$Node key"
      - "field java.util.HashMap$Node value"
      - "method groovy.lang.GString plus java.lang.String"
      - "method groovy.lang.GroovyObject getProperty java.lang.String"
      - "method groovy.text.Template make java.util.Map"
      - "method groovy.text.TemplateEngine createTemplate java.lang.String"
      - "method java.io.File getAbsolutePath"
      - "method java.io.File getCanonicalPath"
      - "method java.io.File getName"
      - "method java.lang.Iterable iterator"
      - "method java.lang.Object clone"
      - "method java.lang.Object toString"
      - "method java.lang.String replaceAll java.lang.String java.lang.String"
      - "method java.lang.String replaceFirst java.lang.String java.lang.String"
      - "method java.text.DateFormat setTimeZone java.util.TimeZone"
      - "method java.text.Format format java.lang.Object"
      - "method java.util.Iterator next"
      - "method java.util.LinkedHashMap$LinkedHashIterator hasNext"
      - "method java.util.Map keySet"
      - "method java.util.Random nextInt int"
      - "method java.util.regex.MatchResult group int"
      - "method java.util.regex.Matcher find"
      - "method org.jenkinsci.plugins.workflow.cps.CpsClosure2 println java.lang.Object"
      - "new groovy.text.SimpleTemplateEngine"
      - "new java.io.File java.lang.String"
      - "new java.io.File java.lang.String java.lang.String"
      - "new java.text.SimpleDateFormat java.lang.String"
      - "new java.util.Date"
      - "new java.util.Random"
      - "new java.util.TreeMap"
      - "staticMethod groovy.json.StringEscapeUtils escapeJava java.lang.String"
      - "staticMethod groovy.lang.GroovySystem getVersion"
      - "staticMethod java.lang.Float parseFloat java.lang.String"
      - "staticMethod java.lang.System getProperty java.lang.String"
      - "staticMethod java.lang.System getenv java.lang.String"
      - "staticMethod java.lang.Thread sleep long"
      - "staticMethod java.util.TimeZone getTimeZone java.lang.String"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods collect java.util.Map groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods each java.util.Map groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods eachFileMatch java.io.File java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods eachWithIndex java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods find java.lang.String java.lang.String groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getText java.io.File"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods inspect java.lang.Object"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Map java.util.Collection"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Map java.util.Map"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods print groovy.lang.Closure java.lang.Object"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods println groovy.lang.Closure java.lang.Object"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods push java.util.List java.lang.Object"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods readLines java.io.File"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods size java.util.regex.Matcher"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods take java.lang.CharSequence int"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods toDouble java.lang.String"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods toInteger java.lang.String"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods write java.io.File java.lang.String"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods write java.io.File java.lang.String java.lang.String"
      - "staticMethod org.codehaus.groovy.runtime.ScriptBytecodeAdapter bitwiseNegate java.lang.Object"
      - "staticMethod org.codehaus.groovy.runtime.ScriptBytecodeAdapter castToType java.lang.Object java.lang.Class"
      - "staticMethod org.codehaus.groovy.runtime.ScriptBytecodeAdapter isCase java.lang.Object java.lang.Object"
# List of groovy init scripts to be executed during Jenkins master start
  InitScripts:
#  - |
#    print 'adding global pipeline libraries, register properties, bootstrap jobs...'
  CustomConfigMap: false

  Ingress:
    Annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    TLS:
      # - secretName: jenkins.cluster.local
      #   hosts:
      #     - jenkins.cluster.local

Agent:
  Enabled: true
  Image: jenkinsci/jnlp-slave
  ImageTag: 3.7-1
  Privileged: false
  Cpu: "200m"
  Memory: "256Mi"

Persistence:
  Enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # ExistingClaim:

  ## If defined, volume.beta.kubernetes.io/storage-class: <StorageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # StorageClass:
  AccessMode: ReadWriteOnce
  Size: 8Gi
  volumes:
#  - name: nothing
#    emptyDir: {}
  mounts:
#  - mountPath: /var/nothing
#    name: nothing
#    readOnly: true
